name: test_splay_tree

on: workflow_dispatch

jobs:
  ubuntu_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: |
        sudo apt install git
        git submodule update --init --recursive
        sudo apt install clang
        sudo apt install cmake
    - name: build
      run: |
        cd SplayTree
        cmake -S . -B build
        cd build
        cmake --build .
    - name: testing
      run: |
        cd SplayTree/build
        ctest